### PR TITLE
Reset Function

### PR DESCRIPTION
**Pull request by ilianabe**
Reset Function + Table for CheckBoxes Group

### CODE REVIEW

**Review by linev — CHANGES_REQUESTED** [review]
Hi @ilianabe 

Why you duplicates data members of the model? 
It is not a proper way, while it just duplicates code in several places.

There is much elegant way of doing this - you can create copy of your original data and set this copy when press Reset button.  Something like this:

         if(msg.indexOf("MODEL:")==0){
            var json = msg.substr(6);
            var data = JSROOT.parse(json);
            if(data) {
               this.getView().setModel(new JSONModel(data));
               this._data = data;
               this._copy = JSROOT.extend({}, data); // this is your copy
            }
         }


And when pressing Reset:

        this.getView().setModel(new JSONModel(this._copy));

**Comment by ilianabe** [comment]
Oh ok, you are right. I have never thought of that. I will try to change it now!

Iliana
________________________________

**Review by linev — APPROVED** [review]
@ilianabe 

You still set separate fields in your Reset function.
I will merge this PR and check if there is more simple way to do this.

**Comment by linev** [comment]
@ilianabe 

Here that I mean about copy of the model

https://github.com/linev/examples/commit/99653ba5ea9bb609793cbeaba45eed1f5a379502

One not need to update each widget separately - just copy initial model values back

**Pull request merged**
