### PR TITLE
Fit panel branch

### PR DESCRIPTION
**Pull request by ilianabe**
Update button for Range

### CODE REVIEW

**Comment by ilianabe** [comment]
I tried to do a cherry pick and the PR from a specific branch

**Comment by linev** [comment]
You still have merge commits, which makes `git rebase` impossible. 
Can you try to remove https://github.com/linev/examples/pull/28/commits/f194b0ecbec6956eef318b3d55e3d5d475dec4c2 from the PR?

**Comment by linev** [comment]
Hi @ilianabe 

You still have some merge commits in PR.
The only I can do - "squash" all your commits in single one.
Is it ok?

**Comment by ilianabe** [comment]
Hi,

I think I was able to remove f194b0e<https://github.com/linev/examples/commit/f194b0ecbec6956eef318b3d55e3d5d475dec4c2> from the PR.
Should I try to make a new PR now?
________________________________

**Comment by linev** [comment]
Hi @ilianabe,

You delete one commit, but add several other commits to this PR. 
And they again make simple rebase impossible.
You should create new branch - starting from current master in **this** repository - and cherry-pick only normal commits

**Comment by ilianabe** [comment]
OK, I will try this, so it's better to remove the last PR.
________________________________

**Comment by linev** [comment]
@ilianabe 
You start again pushing commits in your **bad** branch, which I cannot normally merge
You should do something like:
```
git fetch upstream
git checkout master
git merge upstream/master
git checkout -b pure_chanages
git cherry-pick 1d70cb0 
git cherry-pick 886ec6c
...
git cherry-pick 0fef09a 
git push origin pure_chanages
```

And sumbit PR, using such new branch.
But please select only GOOD commits.

**Comment by linev** [comment]
Some correction to my previous mail - your master branch already screwed-up and includes extra commits. Therefore you should really start from my branch:
```
git fetch upstream
git checkout upstream/master
git checkout -b pure_chanages
git cherry-pick 1d70cb0 
git cherry-pick 886ec6c
...
git cherry-pick 0fef09a 
git push origin pure_chanages
```

And try to reset your master branch that it fully in sync with my master branch - no any extra commits.  Any kind of new code should be done in special branches

**Comment by ilianabe** [comment]
Ok,
I will first try to fix my master
________________________________

**Pull request closed without merging**
